#![cfg(test)]
// Tests that the SUIT Groth16 verifier performs REAL on-chain verification:
//   - accepts a genuine proof generated by the Circom/snarkjs pipeline
//   - rejects a proof checked against tampered public signals
//   - rejects structurally malformed input
//
// The .hex fixtures are produced from the real BLS12-381 trusted setup:
//   npm run compile && node scripts/setup.js && node scripts/prove.js
//   cargo run -p circom-to-soroban-hex -- vk     build/verification_key.json
//   cargo run -p circom-to-soroban-hex -- proof  build/proof.json
//   cargo run -p circom-to-soroban-hex -- public build/public_signals.json

extern crate std;

use soroban_sdk::{Bytes, Env};

use crate::{Groth16Verifier, Groth16VerifierClient, VerifierError};

const VK_HEX: &str = include_str!("test_data/vk.hex");
const PROOF_HEX: &str = include_str!("test_data/proof.hex");
const PUBLIC_HEX: &str = include_str!("test_data/public.hex");

fn decode_hex(s: &str) -> std::vec::Vec<u8> {
    let s = s.trim();
    assert!(s.len() % 2 == 0, "odd hex length");
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("invalid hex"))
        .collect()
}

fn bytes(env: &Env, hex: &str) -> Bytes {
    Bytes::from_slice(env, &decode_hex(hex))
}

fn setup(env: &Env) -> Groth16VerifierClient {
    let id = env.register(Groth16Verifier, ());
    let client = Groth16VerifierClient::new(env, &id);
    client.set_vk(&bytes(env, VK_HEX));
    client
}

#[test]
fn accepts_valid_proof() {
    let env = Env::default();
    let client = setup(&env);
    let ok = client.verify(&bytes(&env, PROOF_HEX), &bytes(&env, PUBLIC_HEX));
    assert!(ok, "a genuine Groth16 proof must verify on-chain");
}

#[test]
fn rejects_tampered_public_signals() {
    let env = Env::default();
    let client = setup(&env);

    // Flip the last byte of the last public signal. Still well-formed bytes,
    // but no longer the value the proof was generated for — the pairing check
    // must fail and return false.
    let mut pub_bytes = decode_hex(PUBLIC_HEX);
    let last = pub_bytes.len() - 1;
    pub_bytes[last] ^= 0x01;
    let tampered = Bytes::from_slice(&env, &pub_bytes);

    let ok = client.verify(&bytes(&env, PROOF_HEX), &tampered);
    assert!(!ok, "a proof must NOT verify against altered public signals");
}

#[test]
fn rejects_malformed_proof_length() {
    let env = Env::default();
    let client = setup(&env);

    // Truncated proof bytes — parser must reject as MalformedProof.
    let mut proof_bytes = decode_hex(PROOF_HEX);
    proof_bytes.truncate(proof_bytes.len() - 10);
    let bad = Bytes::from_slice(&env, &proof_bytes);

    let res = client.try_verify(&bad, &bytes(&env, PUBLIC_HEX));
    assert_eq!(res, Err(Ok(VerifierError::MalformedProof)));
}

#[test]
fn verify_without_vk_errors() {
    let env = Env::default();
    let id = env.register(Groth16Verifier, ());
    let client = Groth16VerifierClient::new(&env, &id);

    let res = client.try_verify(&bytes(&env, PROOF_HEX), &bytes(&env, PUBLIC_HEX));
    assert_eq!(res, Err(Ok(VerifierError::VerificationKeyNotSet)));
}
